# Generated by Django 5.0.2 on 2024-02-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
    ]
